import { type NextPage } from "next";
import Head from "next/head";
import { signIn, signOut, useSession, getSession } from "next-auth/react";
import { useRouter } from "next/router";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col items-center gap-2">
        <AuthShowcase />
      </div>
    </>
  );
};

export default Home;

const AuthShowcase: React.FC = () => {
  let { data: sessionData } = useSession();
  const router = useRouter();
  return (
    <>
      <p className="text-center text-2xl text-black">
        {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
      </p>
      {sessionData && (
        <button
          className="rounded-full bg-black px-10 py-3 font-semibold text-white no-underline transition hover:bg-gray-900"
          onClick={() => {
            router.push("/dashboard");
          }}
        >
          Head Over to Dashbaord {"->"}
        </button>
      )}
      <button
        className="rounded-full bg-black px-10 py-3 font-semibold text-white no-underline transition hover:bg-gray-900"
        onClick={sessionData ? () => void signOut() : () => void signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </button>
    </>
  );
};
